#!/bin/sh

mkdir -p ${HOME}/.local


# install nvim

curl -L https://github.com/neovim/neovim/releases/latest/download/nvim.appimage -o ${HOME}/.local/bin/nvim
chmod u+x ${HOME}/.local/bin/nvim


# install ag

wget https://geoff.greer.fm/ag/releases/the_silver_searcher-2.2.0.tar.gz
tar xzvf the_silver_searcher-2.2.0.tar.gz
cd the_silver_searcher-2.2.0

./configure --prefix=${HOME}/.local
make
make install



